### ISSUE TITLE
Unable to find dynamic libraries on macOS

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/candi#139]
I am on `macOS` catalina. The `candi` installation script went well, and have installed `deal.ii` with the selected dependencies.

Setting up the project with `cmake` works fine, and so does the `make` invocation. But when trying to run the compiled executable of an example (step-52), I get an error:

```
dyld: Library not loaded: libTKBO.11.dylib
  Referenced from: /Users/krishna/deal.ii-candi/deal.II-master/examples/step-52/copy_step_52/./step-52
  Reason: image not found
Abort trap: 6
```

If I manually do `export DYLD_LIBRARY_PATH=""`, then when trying to run the example, I get an error about `superlu_dist` dynamic library missing

```
dyld: Library not loaded: libsuperlu_dist.5.dylib
  Referenced from: /Users/krishna/deal.ii-candi/deal.II-master/examples/step-52/copy_step_52/./step-52
  Reason: image not found
Abort trap: 6
```

I have the following lines in my `~/.bash_profile`
```
source /Users/krishna/deal.ii-candi/configuration/deal.II-master
source /Users/krishna/deal.ii-candi/configuration/enable.sh
```

What is the cause of these issues, and how can we fix them?

**Comment by koecher** [comment]
@krishnakumarg1984 sorry for the late reply and that I don't have good news.

Yes, configuring on macos after a successful build and install with candi is, as far as I know, a nightmare. In the recent years I didn't get it to run due to several issues for my applications. For macOS seems to be work in progress currently. If we have better help for the runtime configuration with dependencies on macos, we will update the documentation.

For your case, you may try to source the superlu conf file as well (or all of this folder) or reduce the number of dependencies to the minimal use case you have.
