### ISSUE TITLE
Candi's boost is deprecated

### ISSUE THREAD

**Issue by rgoermer** [dealii/candi#283]
Hi there, 
The current candi script is set to install deal.II version 9.3.3, which is fine. However, this version [and any newer] use boost version 1.70.0, which is problematic for some of us if not every single boost version is installed on our systems, since in deal.II-toolchain/packages/boost.package it is specified to install version 1.63.0 of boost. 

For someone like me, who just likes to install software with the click of a feq buttons, it was quite the journey to figure out the problem, why deal.II wouldn't work. 

I would be glad, if someone could fix that in the future, to spare others the time of figuring out what's wrong and why. I have done a fix for me now, however I do not know [and don't intend to find out] how the CHECKSUM variables are calculated. 
Kind regards

**Comment by tjhei** [comment]
Thank you for your bug report. I am a bit confused, though. Is boost 1.70 something that is already installed on your system? Candi does not install boost and would install 1.63.

**Comment by rgoermer** [comment]
The problem is, that deal.II-v9.3.3 seems to require boost 1.70. This is specified in <path-to-dealii>/include/deal.II/base/config.h lines 512-521. It is a static assert and suddenly appeared between version [it hasn't been there for deal.II-v9.2]. In my case, my system uses boost 1.67 per standard, and any deal.II related program is doomed to fail due to this static assert. 

Now, I don't know the exact reasons as to why it is included all of a sudden, I just know it's there and it's causing me troubles. 

My rather broot-force fix was to add in <path-to-candi>/deal.II-toolchain/boost.package the line

`VERSION=1_70_0;CHECKSUM=skip`

and then set 

`PACKAGES="${PACKAGES} once:boost"`

in <path-to-candi>/config.cfg so the script will inevitably install the required boost version. 

However, my system seems to be a little tricky on that side, as it doesn't actually use the newly locally installed boost version, but the system path [which is version 1.67]. So after all, it still doesn't work. I am currently reverting back to deal.II-v9.2, but this requirement is made for the master branch of deal.II as well, so if I were to fix things there, I have to get boost to work with deal.II.

**Comment by bangerth** [comment]
What is happening is this:
* During installation of deal.II, the configuration script either did not find your boost installation, or decided that for whatever reason it is unusable. As a consequence, deal.II falls back to the version that is located under `bundled/boost`, which is 1.70.
* Your project then has `#include` directives that, directly or indirectly, reference your systems 1.73 boost installation and the deal.II `config.h` file which has stored that at the time of configuration, deal.II chose the bundled 1.70 installation.

What the error messages is trying to tell you is that this isn't going to end well. You cannot assume that the two versions of BOOST are compatible with each other. If deal.II is configured using its own bundled version (1.70), then you should make sure that your project is also only using that version.

**Comment by rgoermer** [comment]
I can't argue with the first point. 
The second point however can't be. I very precisely try to tell my project which boost to use during the cmake process, using options like -DBOOST_ROOT=... and in CMakeLists.txt itslef something like set (BOOST_ROOT ... ) or went even as far as to use export BOOST_ROOT ...

So in any way I would expect the version of boost I installed deal.ii with to be found, however I get Version 1.67 in any way.

**Comment by bangerth** [comment]
On 3/21/22 01:59, Robin Goermer wrote:
> The second point however can't be. I very precisely try to tell my project 
> which boost to use during the cmake process, using options like 
> -DBOOST_ROOT=... and in CMakeLists.txt itslef something like set (BOOST_ROOT 
> ... ) or went even as far as to use export BOOST_ROOT ...

Why would you need to tell your project where BOOST is at all? Since your 
project is based on deal.II, and deal.II already knows where BOOST is located, 
just use the include paths determined by deal.II. In other words, there is no 
need for your own project to have a call to FindBOOST in its CMakeLists.txt.

**Comment by kinnewig** [comment]
Also from my side many thanks for the feedback!

> Why would you need to tell your project where BOOST is at all? Since your
project is based on deal.II, and deal.II already knows where BOOST is located,
just use the include paths determined by deal.II. In other words, there is no
need for your own project to have a call to FindBOOST in its CMakeLists.txt.

The Problem even occurs when trying to compile the example step-1, which does not have FindBOOST in its CMakeLists.txt.

> The error check about using two conflicting boost versions is in the config header for a reason. I don't expect this to be "fine".
If your project needs boost, I strongly recommend installing a separate version of boost and then pointing deal.II and your project to it. Also double-check that both projects are indeed using the correct paths (for deal.II that would be in detailed.log).

As I have written above, I previously assumed, that deal.II misinterpreted 1.73 as 1.70 (for example by dropping the minor version). Therefore, I had not looked more closely at the problem until now.



> - During installation of deal.II, the configuration script either did not find your boost installation, or decided that for whatever reason it is unusable. As a consequence, deal.II falls back to the version that is located under bundled/boost, which is 1.70.

I took a closer look at this: deal.II does find the installed boost, but for what ever reason it failed the check: `BOOST_SERIALIZATION_USABLE`.
After installing boost version 1.70 and using the linker flag `-lboost_serialization`, boost passed the check `BOOST_SERIALIZATION_USABLE` and everything seems to be working so far.

I am not quite sure, what the origin of the problem is. I will run a few more test. At the moment, my best guess is that it is a problem with our system and not with deal.II or candi.

**Comment by tjhei** [comment]
Feel free to post if you have further issues.

**Comment by jpthiele** [comment]
I have actually found part of the problem. 
First of all the variable name would be BOOST_DIR instead of the BOOST_ROOT @rgoermer tried.
However, calling deal.II's cmake with -DBOOST_DIR=<path_to_our_1.73boost> just completely ignores this and only finds the old version in /usr/local, so deal.II opts to install the bundled boost. 
Comparing FindBOOST.cmake with FindMETIS.cmake (which works with -DMETIS_DIR) I found that FindBOOST does not use BOOST_DIR (or the subsequently defined BOOST_ROOT) as HINT, so I guess that would be the problem.

**Comment by jpthiele** [comment]
Actually HINT is not needed or rather confuses the BoostConfig by some policy I was unable to set.
However, all that was missing was to set policy CMP0074, such that BOOST_ROOT is actually used.
See
https://cmake.org/cmake/help/latest/policy/CMP0074.html#policy:CMP0074

**Comment by jpthiele** [comment]
I can report success as with that policy deal.II was not only able to recognize our local boost installation but also correctly configure the deal.II/config.h file with 1.73.0
