### ISSUE TITLE
candi deal.II build hangs on ld.gold

### ISSUE THREAD

**Issue by naliboff** [dealii/candi#62]
A number of users, myself included, are trying to build deal.II with candi on Blue Waters (cray cluster, https://bluewaters.ncsa.illinois.edu/). 

The build uses the cray.platform configuration from and gets most of the way through the deal.II build (up to `[100%] Built target deal_II`) and then hangs. The cluster administrator found that the process hanging up is `ld.gold`.

Any insights into what might be going on here? I haven't encountered this issue before, but perhaps it's related to deal.II issue [2820](https://github.com/dealii/dealii/issues/2820)?

I'm going to try compiling deal.II without candi, but I imagine the same issue may pop there as well.

**Comment by Rombur** [comment]
Have you tried a different compiler?

**Comment by koecher** [comment]
Your hanging process is the (system?) linker (`ld.gold`).
It looks like that this process can not handle the immense data from the deal.II build. And yes, I think this will also happen for a manual build.
Maybe you should check the if you have enough system memory and use force to use one thread to build (`candi -j 1` option). And give it more time to complete. Depending on the system the linkage can have a duration of several minutes.

**Comment by tjhei** [comment]
Can you try using ``ld`` instead of ``ld.gold``? You can either configure/compile deal.II manually or go into the ``candi/tmp/build/deal.II-v8.5.0/``. The option should be ``-D DEAL_II_COMPILER_HAS_FUSE_LD_GOLD=no``.

Check if the DEAL_II_LINKER_FLAGS in detailed.log then do not contain something like ``-fuse-ld=gold``.

**Comment by naliboff** [comment]
Thanks for the replies all. 

@Rombur - Not yet, but I will do so if the other two suggestions above don't work. We've been using gcc (4.9.3) + mpich and there are a number of other GNU options we can try out.

@koecher - It does appear to be hanging on` ld.gold` and the hanging time at this point has lasted up to more than an hour (at that point the cluster kills the job due to time limits). The exact commands on which the termination occurred are in the attached file. I asked the system admin if there is way to build on a 'development' type node that would have plenty of memory.

@tjhei - I'll give `-D DEAL_II_COMPILER_HAS_FUSE_LD_GOLD=no` in the existing deal.II candi build and see if that works.

Thanks again for the quick suggestions all! 

[dealii-candi-termination-bluewaters.txt](https://github.com/dealii/candi/files/1661120/dealii-candi-termination-bluewaters.txt)

**Comment by naliboff** [comment]
Good news, adding in `-D DEAL_II_COMPILER_HAS_FUSE_LD_GOLD=no` did the trick. Is it worth adding in this option to [cray.platform](https://github.com/dealii/candi/blob/master/deal.II-toolchain/platforms/contributed/cray.platform)?

**Comment by bangerth** [comment]
Cray is such a crazy platform that I'm not at all surprised that something like this happens. I tend to think that it is worthwhile adding this to the platform file with a comment on why. Would you be willing to provide a patch? (And, out of curiosity, what's your version of `gold`?)

We like to use `gold` because it's *so* much faster than old `ld`. That matters to those of us who compile and test a lot, but maybe not as much on platforms where the primary use is to *use* deal.II, as opposed to *developing* it.

**Comment by naliboff** [comment]
The version of `ld.gold` is 1.11. Certainly happy to provide a patch to cray.platform. As an alternative, would it be worth adding a new platform (e.g., bluewaters.platform) if further testing reveals any other required changes?

**Comment by bangerth** [comment]
I couldn't find the exact release date of ld.gold 1.11, but it has been around since at least the beginning of 2016. So it's a bit outdated, but be that as it may. 

I'll defer to the candi folks here about platform files.
