### ISSUE TITLE
Intel MPI and PETSC

### ISSUE THREAD

**Issue by gassmoeller** [dealii/candi#91]
I had two users reporting the same error message (on different clusters) when trying to install deal.II with PETSC via candi (deal.II v9.0.0, default PETSC). Error message in both cases was:

```
-- Found PETSC
-- Could not find a sufficient PETSC installation: PETSC is compiled against a different MPI library than the one deal.II picked up.
-- DEAL_II_WITH_PETSC has unmet external dependencies.
CMake Error at cmake/configure/configure_3_petsc.cmake:122 (MESSAGE):

  

  Could not find the petsc library!

  Could not find a sufficient PETSC installation:

  PETSC has to be compiled against the same MPI library as deal.II but the
  link line of PETSC contains:

    /usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/mpi/intel64/lib/debug_mt/libmpi.so

  which is not listed in MPI_LIBRARIES:

    MPI_LIBRARIES = "/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/mpi/intel64/lib/libmpicxx.so /usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/mpi/intel64/lib/libmpifort.so /usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/mpi/intel64/lib/release_mt/libmpi.so /usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/mpi/intel64/lib/libmpigi.a /lib64/libdl.so /lib64/librt.so /lib64/libpthread.so"

  

  Please ensure that the petsc library version 3.3.0 or newer is installed on
  your computer and is configured with the same mpi options as deal.II
```

Has someone seen similar errors and has a quick fix? For now I just told them to disable PETSC (we do not need it for ASPECT).

**Comment by Rombur** [comment]
It seems that it's the same problem than [here](https://groups.google.com/forum/#!searchin/dealii/petsc$20mpi%7Csort:date/dealii/qaYk0pBj13U/1p88VGI9CQAJ). I guess the problem is that deal and petsc just pick up two different MPI versions because they are both in the path. You can force deal.II to use the MPI library you want using the variable in [`FindMPI`](https://cmake.org/cmake/help/latest/module/FindMPI.html)

**Comment by tjhei** [comment]
Actually, it looks like PETSc is picking up the debug MPI library, which is probably not what you want on a cluster. Can you try using the ``mpivars.sh`` with ``release_mt`` or set ``I_MPI_LIBRARY_KIND`` so that PETSc picks up the other library? See https://software.intel.com/en-us/mpi-developer-reference-linux-compiler-commands

**Comment by koecher** [comment]
@gassmoeller is this closed by the comments giving above for your proposed problem(s)?
Or do you need (or wish to have) some special implementation within candi to resolve it?

**Comment by gassmoeller** [comment]
I have not heard back from the users with the problem and can not reproduce it myself. Let's close this issue for now. We can always reopen when the problem reappears. Thanks for your input!
